### ISSUE TITLE
Next button not working

### ISSUE THREAD

**Issue by sree24** [balaramadurai/hugo-travelify-theme#34]
Hi @balaramadurai,

Thanks for creating Travelify Theme.
On the home page when I click on Next button, it is giving me page not found error.
Even in demo it is going to https://themes.gohugo.io/page/2/
Is there a setting that I need to add in config for this? Can you let me know the steps to fix this problem?

Thanks in advance,
Sree

**Comment by balaramadurai** [comment]
Hello @sree24,
  Thank you for your interest in the Hugo adaptation of the Travelify theme. 

I don't seem to be getting the error - http://balaramadurai.github.io/page/2/

The URL you have given in the issue is https://themes.gohugo.io/page/2/

So, perhaps, the `baseURL` in the config is not set properly. Please check that.

If that doesn't fix the issue, please let me know.

Thanks
Bala

**Comment by balaramadurai** [comment]
@sree24, I checked the theme demo on the Hugo themes page. That is where, the theme doesn't work. 

However, it works well when cloned and used. See example - https://funderfulworld.com (https://funderfulworld.com/page/2/ works fine)

Please do let me know if you need help with cloning or setting your theme for the website.

Bala

**Comment by sree24** [comment]
Thank you for the quick follow up Bala.
My base url is something like https://pages.github.com/companyname/sample-templates/ (this is just sample not exact url)
So for this when I click on Next button, its is going to https://pages.github.com/page/2 instead of https://pages.github.com/companyname/sample-templates/page/2
