### ISSUE TITLE
how to remove all or some share buttons from the posts?

### ISSUE THREAD

**Issue by Oliver2r** [balaramadurai/hugo-travelify-theme#5]
Hi,

is it possible to remove all or some share buttons from posts?
Is is possible to place a simple share button who only show the post URL.
In a post are the share buttons at the top and at the bottom, is it possible to say, place it only at the top or bottom?

In Europe we get the new GDPR and then the privacy is very important and at the website averything who track something is forbidden.

Is it possible at social media buttons at the to of the website also to remove the rss icon?
Is it possible to place there also a icon for a email contact?

Thanks,
Oliver

**Comment by balaramadurai** [comment]
Hello,
  Thank you for taking the time to give me so many thoughtful suggestions. Quite a few in one issue, I would think 😄 

- [X] Remove all or some share buttons from posts
- [ ] Simple share button to show the post URL - I am not sure, I understand this. Can you please give me some example and create another issue, so that I can keep track?
- [X] One of the set of share buttons at top and bottom should be removed
- [X] Removable RSS link
- [X] Email icon
- [X] Email contact
